services:
  app_proxy:
    environment:
      APP_HOST: hzrd149-relatr_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/contextvm/relatr:v0.1.5@sha256:ac7d73a8b915e393077be8c5b3815a2399d1274838ff0754c2997516d57ead48
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}:/usr/src/app/data
    environment:
      SERVER_SECRET_KEY: ${APP_SEED}

