services:
  app_proxy:
    environment:
      APP_HOST: hzrd149-relatr_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/contextvm/relatr:0.1.10@sha256:b46d00cdeea11f07295f44ea8ea330388909cdbfa086e83bd7006f8f45a668f0
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}:/usr/src/app/data
    environment:
      SERVER_SECRET_KEY: ${APP_SEED}

